export interface VulnPattern {
	id: string
	severity: 'critical' | 'high' | 'medium' | 'low'
	category: string
	pattern: RegExp
	description: string
}

export const VULN_PATTERNS: VulnPattern[] = [
	{ id: 'eval-exec', severity: 'critical', category: 'code-execution', pattern: /\beval\s*\(/, description: 'eval() usage' },
	{ id: 'new-function', severity: 'critical', category: 'code-execution', pattern: /new\s+Function\s*\(/, description: 'new Function() constructor' },
	{ id: 'child-process-exec', severity: 'critical', category: 'code-execution', pattern: /child_process.*exec(?:Sync)?\s*\(/, description: 'child_process exec' },
	{ id: 'spawn-shell', severity: 'high', category: 'code-execution', pattern: /spawn\s*\([^)]*shell\s*:\s*true/, description: 'spawn with shell: true' },
	{ id: 'require-child-process', severity: 'high', category: 'code-execution', pattern: /require\s*\(\s*['"]child_process['"]/, description: 'require child_process' },
	{ id: 'import-child-process', severity: 'high', category: 'code-execution', pattern: /import.*from\s+['"]child_process['"]/, description: 'import child_process' },
	{ id: 'process-env-leak', severity: 'high', category: 'credential-leak', pattern: /process\.env(?:\[|\.)\s*(?!NODE_ENV)/, description: 'process.env access (non-NODE_ENV)' },
	{ id: 'hardcoded-key', severity: 'critical', category: 'credential-leak', pattern: /(?:api[_-]?key|secret|password|token)\s*[:=]\s*['"][a-zA-Z0-9]{20,}['"]/, description: 'Hardcoded credential' },
	{ id: 'aws-key', severity: 'critical', category: 'credential-leak', pattern: /AKIA[0-9A-Z]{16}/, description: 'AWS access key' },
	{ id: 'private-key', severity: 'critical', category: 'credential-leak', pattern: /-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----/, description: 'Embedded private key' },
	{ id: 'fs-write', severity: 'medium', category: 'filesystem', pattern: /(?:writeFile|appendFile|createWriteStream)\s*\(/, description: 'Filesystem write operation' },
	{ id: 'fs-unlink', severity: 'high', category: 'filesystem', pattern: /(?:unlink|rmdir|rm)\s*\(/, description: 'File/directory deletion' },
	{ id: 'fs-chmod', severity: 'high', category: 'filesystem', pattern: /(?:chmod|chown)\s*\(/, description: 'Permission change' },
	{ id: 'path-traversal', severity: 'critical', category: 'filesystem', pattern: /\.\.\/?(?:\.\.\/)*/, description: 'Path traversal attempt' },
	{ id: 'symlink-create', severity: 'high', category: 'filesystem', pattern: /(?:symlink|link)Sync?\s*\(/, description: 'Symlink creation' },
	{ id: 'net-http', severity: 'medium', category: 'network', pattern: /(?:http|https)\.(?:get|request|createServer)\s*\(/, description: 'HTTP request/server' },
	{ id: 'net-fetch', severity: 'low', category: 'network', pattern: /\bfetch\s*\(/, description: 'fetch() call' },
	{ id: 'net-socket', severity: 'high', category: 'network', pattern: /(?:net|dgram)\.create(?:Server|Socket)\s*\(/, description: 'Raw socket creation' },
	{ id: 'net-dns', severity: 'medium', category: 'network', pattern: /dns\.(?:resolve|lookup)\s*\(/, description: 'DNS lookup' },
	{ id: 'crypto-weak', severity: 'medium', category: 'crypto', pattern: /createHash\s*\(\s*['"](?:md5|sha1)['"]/, description: 'Weak hash algorithm' },
	{ id: 'math-random', severity: 'medium', category: 'crypto', pattern: /Math\.random\s*\(\)/, description: 'Math.random() for security' },
	{ id: 'prototype-pollution', severity: 'critical', category: 'injection', pattern: /__proto__|constructor\s*\[/, description: 'Prototype pollution' },
	{ id: 'sql-injection', severity: 'critical', category: 'injection', pattern: /(?:SELECT|INSERT|UPDATE|DELETE|DROP).*\$\{/, description: 'SQL injection via template literal' },
	{ id: 'xss-innerhtml', severity: 'high', category: 'injection', pattern: /innerHTML\s*=/, description: 'innerHTML assignment' },
	{ id: 'xss-document-write', severity: 'high', category: 'injection', pattern: /document\.write\s*\(/, description: 'document.write()' },
	{ id: 'dangerous-uri', severity: 'high', category: 'injection', pattern: /javascript\s*:/, description: 'JavaScript URI scheme' },
	{ id: 'vm-module', severity: 'critical', category: 'sandbox-escape', pattern: /require\s*\(\s*['"]vm['"]/, description: 'VM module usage' },
	{ id: 'worker-threads', severity: 'medium', category: 'sandbox-escape', pattern: /require\s*\(\s*['"]worker_threads['"]/, description: 'Worker threads' },
	{ id: 'cluster-module', severity: 'medium', category: 'sandbox-escape', pattern: /require\s*\(\s*['"]cluster['"]/, description: 'Cluster module' },
	{ id: 'native-addon', severity: 'high', category: 'sandbox-escape', pattern: /\.node['"]?\s*\)/, description: 'Native addon loading' },
	{ id: 'dlopen', severity: 'critical', category: 'sandbox-escape', pattern: /process\.dlopen/, description: 'Dynamic library loading' },
	{ id: 'env-manipulation', severity: 'high', category: 'environment', pattern: /process\.env\s*(?:\[.*\]\s*=|\.[\w]+\s*=)/, description: 'Environment variable write' },
	{ id: 'process-exit', severity: 'medium', category: 'environment', pattern: /process\.exit\s*\(/, description: 'process.exit()' },
	{ id: 'global-override', severity: 'high', category: 'environment', pattern: /global(?:This)?\s*\[/, description: 'Global namespace manipulation' },
	{ id: 'buffer-alloc-unsafe', severity: 'medium', category: 'memory', pattern: /Buffer\.allocUnsafe\s*\(/, description: 'Unsafe buffer allocation' },
	{ id: 'large-allocation', severity: 'medium', category: 'memory', pattern: /new\s+(?:Array|Buffer|Uint8Array)\s*\(\s*\d{8,}/, description: 'Large memory allocation' },
	{ id: 'timeout-clear', severity: 'low', category: 'environment', pattern: /clearTimeout\s*\(\s*\d+\)/, description: 'Clearing arbitrary timeouts' },
	{ id: 'infinite-loop', severity: 'medium', category: 'environment', pattern: /while\s*\(\s*true\s*\)/, description: 'Potential infinite loop' },
	{ id: 'obfuscation-hex', severity: 'high', category: 'obfuscation', pattern: /\\x[0-9a-fA-F]{2}(?:\\x[0-9a-fA-F]{2}){5,}/, description: 'Hex-encoded string (obfuscation)' },
	{ id: 'obfuscation-base64', severity: 'medium', category: 'obfuscation', pattern: /atob\s*\(|Buffer\.from\s*\([^)]*,\s*['"]base64['"]/, description: 'Base64 decode' },
	{ id: 'obfuscation-charcode', severity: 'high', category: 'obfuscation', pattern: /String\.fromCharCode\s*\([^)]{20,}\)/, description: 'CharCode obfuscation' },
	{ id: 'data-exfil-post', severity: 'high', category: 'exfiltration', pattern: /(?:fetch|axios|request)\s*\([^)]*method\s*:\s*['"]POST['"]/, description: 'POST request (potential exfiltration)' },
	{ id: 'webhook-arbitrary', severity: 'medium', category: 'exfiltration', pattern: /webhook|callback.*(?:https?:\/\/)/, description: 'Arbitrary webhook URL' },
	{ id: 'stdin-read', severity: 'low', category: 'environment', pattern: /process\.stdin/, description: 'stdin access' },
	{ id: 'debugger-statement', severity: 'low', category: 'environment', pattern: /\bdebugger\b/, description: 'Debugger statement' },
	{ id: 'require-vm2', severity: 'high', category: 'sandbox-escape', pattern: /require\s*\(\s*['"]vm2['"]/, description: 'vm2 module (known escapes)' },
	{ id: 'wasm-instantiate', severity: 'medium', category: 'sandbox-escape', pattern: /WebAssembly\.instantiate/, description: 'WebAssembly instantiation' },
	{ id: 'reflect-construct', severity: 'high', category: 'sandbox-escape', pattern: /Reflect\.construct\s*\(/, description: 'Reflect.construct usage' },
	{ id: 'proxy-handler', severity: 'medium', category: 'sandbox-escape', pattern: /new\s+Proxy\s*\(/, description: 'Proxy object creation' },
	{ id: 'import-meta-resolve', severity: 'low', category: 'sandbox-escape', pattern: /import\.meta\.resolve/, description: 'import.meta.resolve usage' },
]
